Script started on Thu May 24 16:53:07 2012
[?1034hbash-3.2$ make && blitz -g os
kpl TestProgram4 -unsafe
asm TestProgram4.s
lddd UserRuntime.o UserSystem.o TestProgram4.o -o TestProgram4
diskUtil -i
diskUtil -a file1 file1
diskUtil -a MyProgram MyProgram
diskUtil -a TestProgram1 TestProgram1
diskUtil -a TestProgram2 TestProgram2
diskUtil -a TestProgram3 TestProgram3
diskUtil -a TestProgram4 TestProgram4
diskUtil -a file2 file2
diskUtil -a file3 file3
diskUtil -a file1234abcd file1234abcd
diskUtil -a Program1 Program1
diskUtil -a Program2 Program2
diskUtil -a FileWithVeryLongName012345678901234567890123456789 \
			FileWithVeryLongName012345678901234567890123456789
Beginning execution...
====================  KPL PROGRAM STARTING  ====================
Initializing Thread Scheduler...
Initializing Process Manager...
Initializing Thread Manager...
Initializing Frame Manager...
AllocateRandomFrames called.  NUMBER_OF_PHYSICAL_PAGE_FRAMES = 512
Initializing Disk Driver...
Initializing File Manager...

**********  OpenTest1 running  **********

Attempting to open a nonexistent file, which should return -1.
Okay.
Attempting to open a file with an overly large name, which should return -1.
Okay.
Attempting to open an existing file, which should succeed.
Okay.

**********  Test Complete  **********


*****  A 'wait' instruction was executed and no more interrupts are scheduled... halting emulation!  *****

Done!  The next instruction to execute will be:
001138: 09000000       ret     
Number of Disk Reads    = 18
Number of Disk Writes   = 0
Instructions Executed   = 3388679
Time Spent Sleeping     = 20389
    Total Elapsed Time  = 3409068
bash-3.2$ make && blitz -g os
kpl TestProgram4 -unsafe
asm TestProgram4.s
lddd UserRuntime.o UserSystem.o TestProgram4.o -o TestProgram4
diskUtil -i
diskUtil -a file1 file1
diskUtil -a MyProgram MyProgram
diskUtil -a TestProgram1 TestProgram1
diskUtil -a TestProgram2 TestProgram2
diskUtil -a TestProgram3 TestProgram3
diskUtil -a TestProgram4 TestProgram4
diskUtil -a file2 file2
diskUtil -a file3 file3
diskUtil -a file1234abcd file1234abcd
diskUtil -a Program1 Program1
diskUtil -a Program2 Program2
diskUtil -a FileWithVeryLongName012345678901234567890123456789 \
			FileWithVeryLongName012345678901234567890123456789
Beginning execution...
====================  KPL PROGRAM STARTING  ====================
Initializing Thread Scheduler...
Initializing Process Manager...
Initializing Thread Manager...
Initializing Frame Manager...
AllocateRandomFrames called.  NUMBER_OF_PHYSICAL_PAGE_FRAMES = 512
Initializing Disk Driver...
Initializing File Manager...

**********  OpenTest2 running  **********

Attempting to open the same file 10 times.
Open 0 succeeded
Open 1 succeeded
Open 2 succeeded
Open 3 succeeded
Open 4 succeeded
Open 5 succeeded
Open 6 succeeded
Open 7 succeeded
Open 8 succeeded
Open 9 succeeded
Attempting to open the file one more time, which should return -1.
Okay.

**********  Test Complete  **********


*****  A 'wait' instruction was executed and no more interrupts are scheduled... halting emulation!  *****

Done!  The next instruction to execute will be:
001138: 09000000       ret     
Number of Disk Reads    = 18
Number of Disk Writes   = 0
Instructions Executed   = 3451302
Time Spent Sleeping     = 20389
    Total Elapsed Time  = 3471691
bash-3.2$ make && blitz -g os
kpl TestProgram4 -unsafe
asm TestProgram4.s
lddd UserRuntime.o UserSystem.o TestProgram4.o -o TestProgram4
diskUtil -i
diskUtil -a file1 file1
diskUtil -a MyProgram MyProgram
diskUtil -a TestProgram1 TestProgram1
diskUtil -a TestProgram2 TestProgram2
diskUtil -a TestProgram3 TestProgram3
diskUtil -a TestProgram4 TestProgram4
diskUtil -a file2 file2
diskUtil -a file3 file3
diskUtil -a file1234abcd file1234abcd
diskUtil -a Program1 Program1
diskUtil -a Program2 Program2
diskUtil -a FileWithVeryLongName012345678901234567890123456789 \
			FileWithVeryLongName012345678901234567890123456789
Beginning execution...
====================  KPL PROGRAM STARTING  ====================
Initializing Thread Scheduler...
Initializing Process Manager...
Initializing Thread Manager...
Initializing Frame Manager...
AllocateRandomFrames called.  NUMBER_OF_PHYSICAL_PAGE_FRAMES = 512
Initializing Disk Driver...
Initializing File Manager...

**********  OpenCloseTest running  **********

Opening 10 files...
Closing all 10 files...
Opening 10 files...
Closing all 10 files...
Opening 10 files...
Closing all 10 files...
Opening 10 files...
Closing all 10 files...
Opening 10 files...
Closing all 10 files...
Opening 10 files...
Closing all 10 files...
Opening 10 files...
Closing all 10 files...
Opening 10 files...
Closing all 10 files...
Opening 10 files...
Closing all 10 files...
Opening 10 files...
Closing all 10 files...

**********  Test Complete  **********


*****  A 'wait' instruction was executed and no more interrupts are scheduled... halting emulation!  *****

Done!  The next instruction to execute will be:
001138: 09000000       ret     
Number of Disk Reads    = 18
Number of Disk Writes   = 0
Instructions Executed   = 4280434
Time Spent Sleeping     = 20389
    Total Elapsed Time  = 4300823
bash-3.2$ make && blitz -g os
kpl TestProgram4 -unsafe
asm TestProgram4.s
lddd UserRuntime.o UserSystem.o TestProgram4.o -o TestProgram4
diskUtil -i
diskUtil -a file1 file1
diskUtil -a MyProgram MyProgram
diskUtil -a TestProgram1 TestProgram1
diskUtil -a TestProgram2 TestProgram2
diskUtil -a TestProgram3 TestProgram3
diskUtil -a TestProgram4 TestProgram4
diskUtil -a file2 file2
diskUtil -a file3 file3
diskUtil -a file1234abcd file1234abcd
diskUtil -a Program1 Program1
diskUtil -a Program2 Program2
diskUtil -a FileWithVeryLongName012345678901234567890123456789 \
			FileWithVeryLongName012345678901234567890123456789
Beginning execution...
====================  KPL PROGRAM STARTING  ====================
Initializing Thread Scheduler...
Initializing Process Manager...
Initializing Thread Manager...
Initializing Frame Manager...
AllocateRandomFrames called.  NUMBER_OF_PHYSICAL_PAGE_FRAMES = 512
Initializing Disk Driver...
Initializing File Manager...

**********  CloseTest running  **********

Closing files which are not open and invalid file descriptors; should be nops...

**********  Test Complete  **********


*****  A 'wait' instruction was executed and no more interrupts are scheduled... halting emulation!  *****

Done!  The next instruction to execute will be:
001138: 09000000       ret     
Number of Disk Reads    = 18
Number of Disk Writes   = 0
Instructions Executed   = 3369289
Time Spent Sleeping     = 20389
    Total Elapsed Time  = 3389678
bash-3.2$ make && blitz -g os
kpl TestProgram4 -unsafe
asm TestProgram4.s
lddd UserRuntime.o UserSystem.o TestProgram4.o -o TestProgram4
diskUtil -i
diskUtil -a file1 file1
diskUtil -a MyProgram MyProgram
diskUtil -a TestProgram1 TestProgram1
diskUtil -a TestProgram2 TestProgram2
diskUtil -a TestProgram3 TestProgram3
diskUtil -a TestProgram4 TestProgram4
diskUtil -a file2 file2
diskUtil -a file3 file3
diskUtil -a file1234abcd file1234abcd
diskUtil -a Program1 Program1
diskUtil -a Program2 Program2
diskUtil -a FileWithVeryLongName012345678901234567890123456789 \
			FileWithVeryLongName012345678901234567890123456789
Beginning execution...
====================  KPL PROGRAM STARTING  ====================
Initializing Thread Scheduler...
Initializing Process Manager...
Initializing Thread Manager...
Initializing Frame Manager...
AllocateRandomFrames called.  NUMBER_OF_PHYSICAL_PAGE_FRAMES = 512
Initializing Disk Driver...
Initializing File Manager...

**********  ReadTest1 running  **********


Should print '>>>Now is the time for all good m<<<'
              >>>Now is the time for all good m<<<

Should print '>>>en to come to the aid of their<<<'
              >>>en to come to the aid of their<<<

Should print '>>> parties!!!
o the aid of their<<<'
              >>> parties!!!
o the aid of their<<<

Should print '>>> parties!!!
o the aid of their<<<'
              >>> parties!!!
o the aid of their<<<

**********  Test Complete  **********


*****  A 'wait' instruction was executed and no more interrupts are scheduled... halting emulation!  *****

Done!  The next instruction to execute will be:
001138: 09000000       ret     
Number of Disk Reads    = 19
Number of Disk Writes   = 0
Instructions Executed   = 3394759
Time Spent Sleeping     = 49064
    Total Elapsed Time  = 3443823
bash-3.2$ make && blitz -g os
kpl TestProgram4 -unsafe
asm TestProgram4.s
lddd UserRuntime.o UserSystem.o TestProgram4.o -o TestProgram4
diskUtil -i
diskUtil -a file1 file1
diskUtil -a MyProgram MyProgram
diskUtil -a TestProgram1 TestProgram1
diskUtil -a TestProgram2 TestProgram2
diskUtil -a TestProgram3 TestProgram3
diskUtil -a TestProgram4 TestProgram4
diskUtil -a file2 file2
diskUtil -a file3 file3
diskUtil -a file1234abcd file1234abcd
diskUtil -a Program1 Program1
diskUtil -a Program2 Program2
diskUtil -a FileWithVeryLongName012345678901234567890123456789 \
			FileWithVeryLongName012345678901234567890123456789
Beginning execution...
====================  KPL PROGRAM STARTING  ====================
Initializing Thread Scheduler...
Initializing Process Manager...
Initializing Thread Manager...
Initializing Frame Manager...
AllocateRandomFrames called.  NUMBER_OF_PHYSICAL_PAGE_FRAMES = 512
Initializing Disk Driver...
Initializing File Manager...

**********  ReadTest2 running  **********

Reading files which are not open and invalid file descriptors...
Okay
Okay
Okay
Okay
Okay
Okay
Reading with negative sizeInBytes...
Okay
Okay

**********  Test Complete  **********


*****  A 'wait' instruction was executed and no more interrupts are scheduled... halting emulation!  *****

Done!  The next instruction to execute will be:
001138: 09000000       ret     
Number of Disk Reads    = 18
Number of Disk Writes   = 0
Instructions Executed   = 3380764
Time Spent Sleeping     = 20389
    Total Elapsed Time  = 3401153
bash-3.2$ make && blitz -g os
kpl TestProgram4 -unsafe
asm TestProgram4.s
lddd UserRuntime.o UserSystem.o TestProgram4.o -o TestProgram4
diskUtil -i
diskUtil -a file1 file1
diskUtil -a MyProgram MyProgram
diskUtil -a TestProgram1 TestProgram1
diskUtil -a TestProgram2 TestProgram2
diskUtil -a TestProgram3 TestProgram3
diskUtil -a TestProgram4 TestProgram4
diskUtil -a file2 file2
diskUtil -a file3 file3
diskUtil -a file1234abcd file1234abcd
diskUtil -a Program1 Program1
diskUtil -a Program2 Program2
diskUtil -a FileWithVeryLongName012345678901234567890123456789 \
			FileWithVeryLongName012345678901234567890123456789
Beginning execution...
====================  KPL PROGRAM STARTING  ====================
Initializing Thread Scheduler...
Initializing Process Manager...
Initializing Thread Manager...
Initializing Frame Manager...
AllocateRandomFrames called.  NUMBER_OF_PHYSICAL_PAGE_FRAMES = 512
Initializing Disk Driver...
Initializing File Manager...

**********  SeekTest running  **********

Should print 4...
retval = 4
Should print 0...
retval = 0
Should print 72...
retval = 72
Should print -1 (newCurrentPos is > file size)...
retval = -1
Should print -1 (newCurrentPos is < -1)...
retval = -1
Should print -1 (file not open)...
retval = -1
Should print -1 (bad file descriptor)...
retval = -1
Should print 35...
retval = 35

Should print '>>> come to the aid of their part<<<'
              >>> come to the aid of their part<<<

Should print 8...
retval = 8

Should print '>>>he time for all good men to co<<<'
              >>>he time for all good men to co<<<

**********  Test Complete  **********


*****  A 'wait' instruction was executed and no more interrupts are scheduled... halting emulation!  *****

Done!  The next instruction to execute will be:
001138: 09000000       ret     
Number of Disk Reads    = 19
Number of Disk Writes   = 0
Instructions Executed   = 3402001
Time Spent Sleeping     = 47572
    Total Elapsed Time  = 3449573
bash-3.2$ make && blitz -g os
kpl TestProgram4 -unsafe
asm TestProgram4.s
lddd UserRuntime.o UserSystem.o TestProgram4.o -o TestProgram4
diskUtil -i
diskUtil -a file1 file1
diskUtil -a MyProgram MyProgram
diskUtil -a TestProgram1 TestProgram1
diskUtil -a TestProgram2 TestProgram2
diskUtil -a TestProgram3 TestProgram3
diskUtil -a TestProgram4 TestProgram4
diskUtil -a file2 file2
diskUtil -a file3 file3
diskUtil -a file1234abcd file1234abcd
diskUtil -a Program1 Program1
diskUtil -a Program2 Program2
diskUtil -a FileWithVeryLongName012345678901234567890123456789 \
			FileWithVeryLongName012345678901234567890123456789
Beginning execution...
====================  KPL PROGRAM STARTING  ====================
Initializing Thread Scheduler...
Initializing Process Manager...
Initializing Thread Manager...
Initializing Frame Manager...
AllocateRandomFrames called.  NUMBER_OF_PHYSICAL_PAGE_FRAMES = 512
Initializing Disk Driver...
Initializing File Manager...

**********  WriteTest1 running  **********


Should print '>>>abcdefghijklmnopqrst<<<'
              >>>abcdefghijklmnopqrst<<<
Checking that the file contains "abcdefghijklmnopqrst" at position 0...
Okay.

Should print '>>>abcdePONMLklmZYXWVst<<<'
              >>>abcdePONMLklmZYXWVst<<<
Checking that the file contains "abcdePONMLklmZYXWVst" at position 0...
Okay.

**********  Test Complete  **********


*****  A 'wait' instruction was executed and no more interrupts are scheduled... halting emulation!  *****

Done!  The next instruction to execute will be:
001138: 09000000       ret     
Number of Disk Reads    = 19
Number of Disk Writes   = 1
Instructions Executed   = 3421786
Time Spent Sleeping     = 30272
    Total Elapsed Time  = 3452058
bash-3.2$ make && blitz -g os
kpl TestProgram4 -unsafe
asm TestProgram4.s
lddd UserRuntime.o UserSystem.o TestProgram4.o -o TestProgram4
diskUtil -i
diskUtil -a file1 file1
diskUtil -a MyProgram MyProgram
diskUtil -a TestProgram1 TestProgram1
diskUtil -a TestProgram2 TestProgram2
diskUtil -a TestProgram3 TestProgram3
diskUtil -a TestProgram4 TestProgram4
diskUtil -a file2 file2
diskUtil -a file3 file3
diskUtil -a file1234abcd file1234abcd
diskUtil -a Program1 Program1
diskUtil -a Program2 Program2
diskUtil -a FileWithVeryLongName012345678901234567890123456789 \
			FileWithVeryLongName012345678901234567890123456789
Beginning execution...
====================  KPL PROGRAM STARTING  ====================
Initializing Thread Scheduler...
Initializing Process Manager...
Initializing Thread Manager...
Initializing Frame Manager...
AllocateRandomFrames called.  NUMBER_OF_PHYSICAL_PAGE_FRAMES = 512
Initializing Disk Driver...
Initializing File Manager...

**********  WriteTest2 running  **********

Writing files which are not open...
Okay
Okay
Okay
Writing files with invalid file descriptors...
Okay
Okay
Okay
Writing with negative sizeInBytes...
Okay
Okay
Make sure file size is unchanged...
Okay

**********  Test Complete  **********


*****  A 'wait' instruction was executed and no more interrupts are scheduled... halting emulation!  *****

Done!  The next instruction to execute will be:
001138: 09000000       ret     
Number of Disk Reads    = 18
Number of Disk Writes   = 0
Instructions Executed   = 3385497
Time Spent Sleeping     = 20389
    Total Elapsed Time  = 3405886
bash-3.2$ make && blitz -g os
kpl TestProgram4 -unsafe
asm TestProgram4.s
lddd UserRuntime.o UserSystem.o TestProgram4.o -o TestProgram4
diskUtil -i
diskUtil -a file1 file1
diskUtil -a MyProgram MyProgram
diskUtil -a TestProgram1 TestProgram1
diskUtil -a TestProgram2 TestProgram2
diskUtil -a TestProgram3 TestProgram3
diskUtil -a TestProgram4 TestProgram4
diskUtil -a file2 file2
diskUtil -a file3 file3
diskUtil -a file1234abcd file1234abcd
diskUtil -a Program1 Program1
diskUtil -a Program2 Program2
diskUtil -a FileWithVeryLongName012345678901234567890123456789 \
			FileWithVeryLongName012345678901234567890123456789
Beginning execution...
====================  KPL PROGRAM STARTING  ====================
Initializing Thread Scheduler...
Initializing Process Manager...
Initializing Thread Manager...
Initializing Frame Manager...
AllocateRandomFrames called.  NUMBER_OF_PHYSICAL_PAGE_FRAMES = 512
Initializing Disk Driver...
Initializing File Manager...

**********  WriteTest3 running  **********

Writing "abcdefghijklmnopqrstuvwxyz" to position 0 in file...
Okay
Writing "zyxwvutsrqponmlkjihgfedcba" to position 8179 in file...
Okay
Writing "aaaaabbbbbcccccdddddeeeeef" to position 16371 in file...
Okay
Writing "ggggghhhhhiiiiijjjjjkkkkkl" to position 24550 in file...
Okay
Checking that the file contains "abcdefghijklmnopqrstuvwxyz" at position 0...
Okay.
Checking that the file contains "zyxwvutsrqponmlkjihgfedcba" at position 8179...
Okay.
Checking that the file contains "aaaaabbbbbcccccdddddeeeeef" at position 16371...
Okay.
Checking that the file contains "ggggghhhhhiiiiijjjjjkkkkkl" at position 24550...
Okay.
Writing "AAAABBBBCCCCDDDDEEEEFFFFGG" to position 16371 in file...
Okay
Writing "ABCDEFGHIJKLMNOPQRSTUVWXYZ" to position 0 in file...
Okay
Writing "HHHHIIIIJJJJKKKKLLLLMMMMNN" to position 24550 in file...
Okay
Writing "ZYXWVUTSRQPONMLKJIHGFEDCBA" to position 8179 in file...
Okay
Checking that the file contains "ABCDEFGHIJKLMNOPQRSTUVWXYZ" at position 0...
Okay.
Checking that the file contains "ZYXWVUTSRQPONMLKJIHGFEDCBA" at position 8179...
Okay.
Checking that the file contains "AAAABBBBCCCCDDDDEEEEFFFFGG" at position 16371...
Okay.
Checking that the file contains "HHHHIIIIJJJJKKKKLLLLMMMMNN" at position 24550...
Okay.

**********  Test Complete  **********


*****  A 'wait' instruction was executed and no more interrupts are scheduled... halting emulation!  *****

Done!  The next instruction to execute will be:
001138: 09000000       ret     
Number of Disk Reads    = 33
Number of Disk Writes   = 9
Instructions Executed   = 3549529
Time Spent Sleeping     = 30751
    Total Elapsed Time  = 3580280
bash-3.2$ make && blitz -g os
kpl TestProgram4 -unsafe
asm TestProgram4.s
lddd UserRuntime.o UserSystem.o TestProgram4.o -o TestProgram4
diskUtil -i
diskUtil -a file1 file1
diskUtil -a MyProgram MyProgram
diskUtil -a TestProgram1 TestProgram1
diskUtil -a TestProgram2 TestProgram2
diskUtil -a TestProgram3 TestProgram3
diskUtil -a TestProgram4 TestProgram4
diskUtil -a file2 file2
diskUtil -a file3 file3
diskUtil -a file1234abcd file1234abcd
diskUtil -a Program1 Program1
diskUtil -a Program2 Program2
diskUtil -a FileWithVeryLongName012345678901234567890123456789 \
			FileWithVeryLongName012345678901234567890123456789
Beginning execution...
====================  KPL PROGRAM STARTING  ====================
Initializing Thread Scheduler...
Initializing Process Manager...
Initializing Thread Manager...
Initializing Frame Manager...
AllocateRandomFrames called.  NUMBER_OF_PHYSICAL_PAGE_FRAMES = 512
Initializing Disk Driver...
Initializing File Manager...

**********  WriteTest4 running  **********

Writing "abcdefghijklmnopqrstuvwxyz" to position 0 in file...
Okay
Checking that the file contains "abcdefghijklmnopqrstuvwxyz" at position 0...
Okay.
Writing "0123" to current position...
Okay
Writing "ABC" to current position...
Okay
Writing "4567" to current position...
Okay
Writing "DEF" to current position...
Okay
Writing "89" to current position...
Okay
Writing "GHI" to current position...
Okay
Checking that the file contains "abc0123ABC4567DEF89GHIwxyz" at position 0...
Okay.

**********  Test Complete  **********


*****  A 'wait' instruction was executed and no more interrupts are scheduled... halting emulation!  *****

Done!  The next instruction to execute will be:
001138: 09000000       ret     
Number of Disk Reads    = 19
Number of Disk Writes   = 4
Instructions Executed   = 4324688
Time Spent Sleeping     = 29881
    Total Elapsed Time  = 4354569
bash-3.2$ make && blitz -g os
kpl TestProgram4 -unsafe
asm TestProgram4.s
lddd UserRuntime.o UserSystem.o TestProgram4.o -o TestProgram4
diskUtil -i
diskUtil -a file1 file1
diskUtil -a MyProgram MyProgram
diskUtil -a TestProgram1 TestProgram1
diskUtil -a TestProgram2 TestProgram2
diskUtil -a TestProgram3 TestProgram3
diskUtil -a TestProgram4 TestProgram4
diskUtil -a file2 file2
diskUtil -a file3 file3
diskUtil -a file1234abcd file1234abcd
diskUtil -a Program1 Program1
diskUtil -a Program2 Program2
diskUtil -a FileWithVeryLongName012345678901234567890123456789 \
			FileWithVeryLongName012345678901234567890123456789
Beginning execution...
====================  KPL PROGRAM STARTING  ====================
Initializing Thread Scheduler...
Initializing Process Manager...
Initializing Thread Manager...
Initializing Frame Manager...
AllocateRandomFrames called.  NUMBER_OF_PHYSICAL_PAGE_FRAMES = 512
Initializing Disk Driver...
Initializing File Manager...

**********  WriteTest5 running  **********

Writing "abcdefghijklmnopqrstuvwxyz" to position 0 in file...
Okay
Checking that the file contains "abcdefghijklmnopqrstuvwxyz" at position 0...
Okay.
Writing "abcdefghijklmnopqrstuvwxyz" to position 8192 in file...
Okay
Checking that the file contains "abcdefghijklmnopqrstuvwxyz" at position 8192...
Okay.
Make sure that the activity of child 1 and child 2 is interleaved.
......Child 1 beginning......
......Child 2 beginning......
Writing "B" to position 1 in file...
Okay
Writing "N" to position 8205 in file...
Okay
Writing "D" to position 3 in file...
Okay
Writing "P" to position 8207 in file...
Okay
Writing "F" to position 5 in file...
Okay
Writing "R" to position 8209 in file...
Okay
Writing "T" to position 8211 in file...
Okay
Writing "V" to position 8213 in file...
Okay
Writing "H" to position 7 in file...
Okay
Writing "J" to position 9 in file...
Okay
Writing "L" to position 11 in file...
Okay
Writing "X" to position 8215 in file...
Okay
......Child 2 ending......
Writing "A" to position 0 in file...
Okay
Writing "M" to position 8204 in file...
Okay
Writing "C" to position 2 in file...
Okay
Writing "O" to position 8206 in file...
Okay
Writing "E" to position 4 in file...
Okay
Writing "Q" to position 8208 in file...
Okay
Writing "G" to position 6 in file...
Okay
Writing "I" to position 8 in file...
Okay
Writing "K" to position 10 in file...
Okay
Writing "S" to position 8210 in file...
Okay
Writing "U" to position 8212 in file...
Okay
Writing "W" to position 8214 in file...
Okay
......Child 1 ending......
Checking that the file contains "ABCDEFGHIJKLmnopqrstuvwxyz" at position 0...
Okay.
Checking that the file contains "abcdefghijklMNOPQRSTUVWXyz" at position 8192...
Okay.

**********  Test Complete  **********


*****  A 'wait' instruction was executed and no more interrupts are scheduled... halting emulation!  *****

Done!  The next instruction to execute will be:
001138: 09000000       ret     
Number of Disk Reads    = 38
Number of Disk Writes   = 18
Instructions Executed   = 4758971
Time Spent Sleeping     = 29899
    Total Elapsed Time  = 4788870
bash-3.2$ make && blitz -g os
kpl TestProgram4 -unsafe
asm TestProgram4.s
lddd UserRuntime.o UserSystem.o TestProgram4.o -o TestProgram4
diskUtil -i
diskUtil -a file1 file1
diskUtil -a MyProgram MyProgram
diskUtil -a TestProgram1 TestProgram1
diskUtil -a TestProgram2 TestProgram2
diskUtil -a TestProgram3 TestProgram3
diskUtil -a TestProgram4 TestProgram4
diskUtil -a file2 file2
diskUtil -a file3 file3
diskUtil -a file1234abcd file1234abcd
diskUtil -a Program1 Program1
diskUtil -a Program2 Program2
diskUtil -a FileWithVeryLongName012345678901234567890123456789 \
			FileWithVeryLongName012345678901234567890123456789
Beginning execution...
====================  KPL PROGRAM STARTING  ====================
Initializing Thread Scheduler...
Initializing Process Manager...
Initializing Thread Manager...
Initializing Frame Manager...
AllocateRandomFrames called.  NUMBER_OF_PHYSICAL_PAGE_FRAMES = 512
Initializing Disk Driver...
Initializing File Manager...

**********  ReadTest3 running  **********

Should print 9 lines with the characters 'Now is th'.
Each line should contain only one character.
N--------
-o-------
--w------
--- -----
----i----
-----s---
------ --
-------t-
--------h
Should print 9 lines with the characters 'e time fo'.
Each line should contain only one character.
e--------
- -------
--t------
---i-----
----m----
-----e---
------ --
-------f-
--------o
Should print 9 lines with the characters 'r all goo'.
Each line should contain only one character.
r--------
- -------
--a------
---l-----
----l----
----- ---
------g--
-------o-
--------o

**********  Test Complete  **********


*****  A 'wait' instruction was executed and no more interrupts are scheduled... halting emulation!  *****

Done!  The next instruction to execute will be:
001138: 09000000       ret     
Number of Disk Reads    = 19
Number of Disk Writes   = 0
Instructions Executed   = 11504771
Time Spent Sleeping     = 48972
    Total Elapsed Time  = 11553743
bash-3.2$ make && blitz -g os
kpl TestProgram4 -unsafe
asm TestProgram4.s
lddd UserRuntime.o UserSystem.o TestProgram4.o -o TestProgram4
diskUtil -i
diskUtil -a file1 file1
diskUtil -a MyProgram MyProgram
diskUtil -a TestProgram1 TestProgram1
diskUtil -a TestProgram2 TestProgram2
diskUtil -a TestProgram3 TestProgram3
diskUtil -a TestProgram4 TestProgram4
diskUtil -a file2 file2
diskUtil -a file3 file3
diskUtil -a file1234abcd file1234abcd
diskUtil -a Program1 Program1
diskUtil -a Program2 Program2
diskUtil -a FileWithVeryLongName012345678901234567890123456789 \
			FileWithVeryLongName012345678901234567890123456789
Beginning execution...
====================  KPL PROGRAM STARTING  ====================
Initializing Thread Scheduler...
Initializing Process Manager...
Initializing Thread Manager...
Initializing Frame Manager...
AllocateRandomFrames called.  NUMBER_OF_PHYSICAL_PAGE_FRAMES = 512
Initializing Disk Driver...
Initializing File Manager...

**********  ReadTest4 running  **********

Okay.
Okay.
Okay.
Okay.
Okay.
Okay.
Okay.
Okay.
Okay.
Okay.
Okay.
Okay.

**********  Test Complete  **********


*****  A 'wait' instruction was executed and no more interrupts are scheduled... halting emulation!  *****

Done!  The next instruction to execute will be:
001138: 09000000       ret     
Number of Disk Reads    = 19
Number of Disk Writes   = 0
Instructions Executed   = 3401678
Time Spent Sleeping     = 48172
    Total Elapsed Time  = 3449850
bash-3.2$ make && blitz -g os
kpl TestProgram4 -unsafe
asm TestProgram4.s
lddd UserRuntime.o UserSystem.o TestProgram4.o -o TestProgram4
diskUtil -i
diskUtil -a file1 file1
diskUtil -a MyProgram MyProgram
diskUtil -a TestProgram1 TestProgram1
diskUtil -a TestProgram2 TestProgram2
diskUtil -a TestProgram3 TestProgram3
diskUtil -a TestProgram4 TestProgram4
diskUtil -a file2 file2
diskUtil -a file3 file3
diskUtil -a file1234abcd file1234abcd
diskUtil -a Program1 Program1
diskUtil -a Program2 Program2
diskUtil -a FileWithVeryLongName012345678901234567890123456789 \
			FileWithVeryLongName012345678901234567890123456789
Beginning execution...
====================  KPL PROGRAM STARTING  ====================
Initializing Thread Scheduler...
Initializing Process Manager...
Initializing Thread Manager...
Initializing Frame Manager...
AllocateRandomFrames called.  NUMBER_OF_PHYSICAL_PAGE_FRAMES = 512
Initializing Disk Driver...
Initializing File Manager...

**********  WriteTest6 running  **********

Initializing data array to ABCDEFGHIJKLMNOPQRSTUVWXYZ...
Writing 10000 bytes to pos 0...
Initializing data array to abcdefghijklmnopqrstuvwxyz...
Writing 10000 bytes to pos 10000...
Checking that the file contains "ABCDEFGHIJKLMNOPQRSTUVWXYZ" at position 0...
Okay.
Checking that the file contains "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPabcdefghijklmnopqrstuvwxyz" at position 9958...
Okay.
Checking that the file contains "abcdefghijklmnopqrstuvwxyzabcdefghijklmnop" at position 19958...
Okay.
Checking that the file contains "ABCDEFGHIJKLMNOPQRSTUVWXYZ" at position 3900...
Okay.
Checking that the file contains "abcdefghijklmnopqrstuvwxyz" at position 13900...
Okay.
Initializing data array to ABCDEFGHIJKLMNOPQRSTUVWXYZ...
Checking 10000 bytes at pos 0...
Initializing data array to abcdefghijklmnopqrstuvwxyz...
Checking 10000 bytes at pos 10000...
Initializing data array to ZYXWVUTSRQPONMLKJIHGFEDCBA...
Writing 10000 bytes to pos 0...
Initializing data array to zyxwvutsrqponmlkjihgfedcba...
Writing 10000 bytes to pos 10000...
Checking that the file contains "ZYXWVUTSRQPONMLKJIHGFEDCBA" at position 0...
Okay.
Checking that the file contains "ZYXWVUTSRQPONMLKJIHGFEDCBAZYXWVUTSRQPONMLKzyxwvutsrqponmlkjihgfedcba" at position 9958...
Okay.
Checking that the file contains "zyxwvutsrqponmlkjihgfedcbazyxwvutsrqponmlk" at position 19958...
Okay.
Checking that the file contains "ZYXWVUTSRQPONMLKJIHGFEDCBA" at position 3900...
Okay.
Checking that the file contains "zyxwvutsrqponmlkjihgfedcba" at position 13900...
Okay.
Initializing data array to ZYXWVUTSRQPONMLKJIHGFEDCBA...
Checking 10000 bytes at pos 0...
Initializing data array to zyxwvutsrqponmlkjihgfedcba...
Checking 10000 bytes at pos 10000...

**********  Test Complete  **********


*****  A 'wait' instruction was executed and no more interrupts are scheduled... halting emulation!  *****

Done!  The next instruction to execute will be:
001138: 09000000       ret     
Number of Disk Reads    = 40
Number of Disk Writes   = 6
Instructions Executed   = 7525905
Time Spent Sleeping     = 31606
    Total Elapsed Time  = 7557511
bash-3.2$ make && blitz -g os
kpl TestProgram4 -unsafe
asm TestProgram4.s
lddd UserRuntime.o UserSystem.o TestProgram4.o -o TestProgram4
diskUtil -i
diskUtil -a file1 file1
diskUtil -a MyProgram MyProgram
diskUtil -a TestProgram1 TestProgram1
diskUtil -a TestProgram2 TestProgram2
diskUtil -a TestProgram3 TestProgram3
diskUtil -a TestProgram4 TestProgram4
diskUtil -a file2 file2
diskUtil -a file3 file3
diskUtil -a file1234abcd file1234abcd
diskUtil -a Program1 Program1
diskUtil -a Program2 Program2
diskUtil -a FileWithVeryLongName012345678901234567890123456789 \
			FileWithVeryLongName012345678901234567890123456789
Beginning execution...
====================  KPL PROGRAM STARTING  ====================
Initializing Thread Scheduler...
Initializing Process Manager...
Initializing Thread Manager...
Initializing Frame Manager...
AllocateRandomFrames called.  NUMBER_OF_PHYSICAL_PAGE_FRAMES = 512
Initializing Disk Driver...
Initializing File Manager...

**********  OpenTest3 running  **********

Attempting to open an existing file whose name exceeds the maximum.
Okay.
Okay.
Attempting to open an existing file using a string which crosses a page boundary.
Okay.

**********  Test Complete  **********


*****  A 'wait' instruction was executed and no more interrupts are scheduled... halting emulation!  *****

Done!  The next instruction to execute will be:
001138: 09000000       ret     
Number of Disk Reads    = 18
Number of Disk Writes   = 0
Instructions Executed   = 3384009
Time Spent Sleeping     = 20389
    Total Elapsed Time  = 3404398
bash-3.2$ make && blitz -g os
kpl TestProgram4 -unsafe
asm TestProgram4.s
lddd UserRuntime.o UserSystem.o TestProgram4.o -o TestProgram4
diskUtil -i
diskUtil -a file1 file1
diskUtil -a MyProgram MyProgram
diskUtil -a TestProgram1 TestProgram1
diskUtil -a TestProgram2 TestProgram2
diskUtil -a TestProgram3 TestProgram3
diskUtil -a TestProgram4 TestProgram4
diskUtil -a file2 file2
diskUtil -a file3 file3
diskUtil -a file1234abcd file1234abcd
diskUtil -a Program1 Program1
diskUtil -a Program2 Program2
diskUtil -a FileWithVeryLongName012345678901234567890123456789 \
			FileWithVeryLongName012345678901234567890123456789
Beginning execution...
====================  KPL PROGRAM STARTING  ====================
Initializing Thread Scheduler...
Initializing Process Manager...
Initializing Thread Manager...
Initializing Frame Manager...
AllocateRandomFrames called.  NUMBER_OF_PHYSICAL_PAGE_FRAMES = 512
Initializing Disk Driver...
Initializing File Manager...

**********  ExecTest1 running  **********

Should print 'Hello, world'...
Hello, World!!!

**********  Test Complete  **********


*****  A 'wait' instruction was executed and no more interrupts are scheduled... halting emulation!  *****

Done!  The next instruction to execute will be:
001138: 09000000       ret     
Number of Disk Reads    = 25
Number of Disk Writes   = 0
Instructions Executed   = 3530882
Time Spent Sleeping     = 30792
    Total Elapsed Time  = 3561674
bash-3.2$ make && blitz -g os
kpl TestProgram4 -unsafe
asm TestProgram4.s
lddd UserRuntime.o UserSystem.o TestProgram4.o -o TestProgram4
diskUtil -i
diskUtil -a file1 file1
diskUtil -a MyProgram MyProgram
diskUtil -a TestProgram1 TestProgram1
diskUtil -a TestProgram2 TestProgram2
diskUtil -a TestProgram3 TestProgram3
diskUtil -a TestProgram4 TestProgram4
diskUtil -a file2 file2
diskUtil -a file3 file3
diskUtil -a file1234abcd file1234abcd
diskUtil -a Program1 Program1
diskUtil -a Program2 Program2
diskUtil -a FileWithVeryLongName012345678901234567890123456789 \
			FileWithVeryLongName012345678901234567890123456789
Beginning execution...
====================  KPL PROGRAM STARTING  ====================
Initializing Thread Scheduler...
Initializing Process Manager...
Initializing Thread Manager...
Initializing Frame Manager...
AllocateRandomFrames called.  NUMBER_OF_PHYSICAL_PAGE_FRAMES = 512
Initializing Disk Driver...
Initializing File Manager...

**********  ExecTest2 running  **********

Attempting to exec an existing file whose name exceeds the maximum.
Okay.
Attempting to exec an existing file which is not an executable.
LoadExecutable: Bad magic number
Okay.
Attempting to open an existing file using a string which crosses a page boundary.
Should print 'Hello, world'...
Hello, World!!!

**********  Test Complete  **********


*****  A 'wait' instruction was executed and no more interrupts are scheduled... halting emulation!  *****

Done!  The next instruction to execute will be:
001138: 09000000       ret     
Number of Disk Reads    = 26
Number of Disk Writes   = 0
Instructions Executed   = 3549009
Time Spent Sleeping     = 85791
    Total Elapsed Time  = 3634800
bash-3.2$ make && blitz -g os
kpl TestProgram4 -unsafe
asm TestProgram4.s
lddd UserRuntime.o UserSystem.o TestProgram4.o -o TestProgram4
diskUtil -i
diskUtil -a file1 file1
diskUtil -a MyProgram MyProgram
diskUtil -a TestProgram1 TestProgram1
diskUtil -a TestProgram2 TestProgram2
diskUtil -a TestProgram3 TestProgram3
diskUtil -a TestProgram4 TestProgram4
diskUtil -a file2 file2
diskUtil -a file3 file3
diskUtil -a file1234abcd file1234abcd
diskUtil -a Program1 Program1
diskUtil -a Program2 Program2
diskUtil -a FileWithVeryLongName012345678901234567890123456789 \
			FileWithVeryLongName012345678901234567890123456789
Beginning execution...
====================  KPL PROGRAM STARTING  ====================
Initializing Thread Scheduler...
Initializing Process Manager...
Initializing Thread Manager...
Initializing Frame Manager...
AllocateRandomFrames called.  NUMBER_OF_PHYSICAL_PAGE_FRAMES = 512
Initializing Disk Driver...
Initializing File Manager...

**********  ExecTest3 running  **********

Should print 'Hello, world' 20 times...
Hello, world      1
Hello, world      2
Hello, world      3
Hello, world      4
Hello, world      5
Hello, world      6
Hello, world      7
Hello, world      8
Hello, world      9
Hello, world      10
Hello, world      11
Hello, world      12
Hello, world      13
Hello, world      14
Hello, world      15
Hello, world      16
Hello, world      17
Hello, world      18
Hello, world      19
Hello, world      20

**********  Test Complete  **********


*****  A 'wait' instruction was executed and no more interrupts are scheduled... halting emulation!  *****

Done!  The next instruction to execute will be:
001138: 09000000       ret     
Number of Disk Reads    = 159
Number of Disk Writes   = 1
Instructions Executed   = 6806935
Time Spent Sleeping     = 220593
    Total Elapsed Time  = 7027528
bash-3.2$ exit

Script done on Thu May 24 16:55:24 2012
