// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef gui_h
#define gui_h
#include <FL/Fl.H>
#ifdef NEEDVSNPRINTF
#include <stdarg.h>
extern int vsnprintf (char *, unsigned int, const char *, va_list); 
#endif
#include "game.h"
extern int debug; 
extern Game game; 
extern void readgame(int &,char **&); 
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *MainWin;
#include "PlayArea.h"
extern PlayArea *play_area;
#include <FL/Fl_Browser.H>
extern Fl_Browser *gui_textout;
#include <FL/Fl_Output.H>
extern Fl_Output *gui_level;
extern Fl_Output *gui_gold;
extern Fl_Output *gui_health;
#include <FL/Fl_Button.H>
extern Fl_Button *gui_west;
extern Fl_Button *gui_north;
extern Fl_Button *gui_south;
extern Fl_Button *gui_east;
extern Fl_Button *gui_down;
extern Fl_Button *gui_up;
#include <FL/Fl_Input.H>
extern Fl_Input *gui_in;
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Item menu_[];
void gui_message(char *fmt, ...);
#endif
